### ISSUE TITLE
About the PPI performance

### ISSUE THREAD

**Issue by cenyk1230** [Namkyeong/BGRL_Pytorch#2]
Hi, thank you for the great work. I wonder whether there is code for reproducing the PPI performance of BGRL (70.49 reported in Table 6).

**Comment by Namkyeong** [comment]
Hello, thank you for your interest in my repos.

Actually, I'm not an author of BGRL.
Since there was no available official source code when I created this repository, I tried my best to implement BGRL following the paper.
But now, author's official source code is available!
https://github.com/nerdslab/bgrl

You can also find out the code for PPI dataset.

Thank you.

**Comment by cenyk1230** [comment]
Many thanks!
